version: '3'

services:
  notifier:
    container_name: notifier
    image:  ghcr.io/flyitalyadsb/new_receivers_notifier
    #build: ./
    restart: unless-stopped
    command:
      - "--from-email=${FROM}"
      - "--to=${TO}"
      - "--server=${SERVER}"
      - "--password=${PASSWORD}"
    volumes:
      - ${MLAT_SERVER_A_WORKDIR_PATH}:/data