version: '3'

services:
  notifier:
    #image:  ghcr.io/flyitalyadsb/new_receivers_notifier
    build: ./
    command:
      --from_email=${FROM}
      --to=${TO}
      --server=${SERVER}
      --password=${PASSWORD}
    volumes:
      - ${MLAT_SERVER_A_WORKDIR_PATH}:/data