version: '3'

services:
  notifier:
    image:  ghcr.io/flyitalyadsb/new_receivers_notifier
    #build: ./
    environment:
      CLIENTS_JSON: ${CLIENTS_JSON}
      FROM: ${FROM}
      TO: ${TO}
      SERVER: ${SERVER}
      PASSWORD: ${PASSWORD}
    volumes:
      - ${MLAT_SERVER_A_WORKDIR_PATH}:/data